Controllers/TaskController.cs
using MyTasks.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace MyTasks.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        [HttpGet]
        public ActionResult Add(int id)
        {
            TaskModel model = new TaskModel();
            model.ProjectId = id;
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(TaskModel model)
        {
            TempData["message"] = "";

            if (ModelState.IsValid)
            {
                try
                {

                    Task task = new Task
                    {
                        Title = model.Title,
                        AddedOn = DateTime.Now,
                        Importance = model.Importance,
                        Status = model.Status,
                        ProjectId = model.ProjectId
                    };

                    if (model.DueDate != null &&  model.DueDate.Length > 0)
                        task.DueDate = DateTime.Parse(model.DueDate);
                    else
                        task.DueDate = null;

                    using (MyTasksContext ctx = new MyTasksContext())
                    {
                        ctx.Tasks.Add(task);
                        ctx.SaveChanges();
                        TempData["message"] = "A tarefa foi adicionada com sucesso !";
                    }
                    return RedirectToAction("Add");

                }
                catch (Exception ex)
                {
                    TempData["message"] = "A tarefa não pode ser adicionada.";
                    System.Web.HttpContext.Current.Trace.Write("TaskController.Add() --> " + ex.Message);
                    return View(model);
                }
            }
            else
            {
                TempData["message"] = "Informe um valor válido !";
                return View(model);
            }

        } // Add

        [HttpGet]
        public ActionResult List(int id)
        {

            // get list of tasks in a project
            using (MyTasksContext ctx = new MyTasksContext())
            {
                var project =(from p in ctx.Projects
                              where p.Id == id
                              select p).SingleOrDefault();

                ViewBag.ProjectTitle = project.Title;

                var tasks = from t in ctx.Tasks.ToList<Task>()
                            where t.ProjectId == id
                            select t;

                return View(tasks);
            }
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            using (MyTasksContext ctx = new MyTasksContext())
            {
                var task = (from t in ctx.Tasks
                            where t.Id == id
                            select t).SingleOrDefault();

                var projectid = task.ProjectId;
                ctx.Tasks.Remove(task);
                ctx.SaveChanges();

                return RedirectToAction("List", new { Id = projectid });
            }
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            using (MyTasksContext ctx = new MyTasksContext())
            {
                var task = (from t in ctx.Tasks.Include("Project")
                            where t.Id == id
                            select t).SingleOrDefault();

                return View(task);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            using (MyTasksContext ctx = new MyTasksContext())
            {
                var task = (from t in ctx.Tasks
                            where t.Id == id
                            select t).SingleOrDefault();

                return View(task);
            }
        }

        [HttpPost]
        public ActionResult Edit(Task newTask)
        {
            using (MyTasksContext ctx = new MyTasksContext())
            {
                var task = (from t in ctx.Tasks
                            where t.Id == newTask.Id
                            select t).SingleOrDefault();

                try
                {
                    task.Title = newTask.Title;
                    task.DueDate = newTask.DueDate;
                    task.Importance = newTask.Importance;
                    task.Status = newTask.Status;

                    ctx.SaveChanges();

                    TempData["message"] = "A tarefa foi atualizada com sucesso !";
                }
                catch (Exception ex)
                {
                    System.Web.HttpContext.Current.Trace.Write("TaskController.Edit() --> " + ex.Message);
                    TempData["message"] = "A tarefa não foi atualizada !";
                }

                return View(task);
            }// using 
        } // Edit 

        [HttpGet]
        public ActionResult SearchForm()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Search(string title)
        {
            using (MyTasksContext ctx = new MyTasksContext())
            {
                var tasks = from t in ctx.Tasks.Include ("Project").ToList<Task>()
                            where t.Project.UserId ==  Int32.Parse( Session["userid"].ToString ())
                                        &&  t.Title.ToUpper().Contains(title.ToUpper())
                            orderby t.DueDate
                            select t;

                return PartialView("SearchResults", tasks);
            }
        }

    }
}

Controllers/UserController.cs
using MyTasks.Models;
using System;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;
using System.Web.Security;

namespace MyTasks.Controllers
{
    public class UserController : Controller
    {
       
        public ActionResult Login()
        {
            LoginModel model = new LoginModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (MyTasksContext ctx = new MyTasksContext())
                    {
                        var user = (from u in ctx.Users 
                                   where u.Email == model.Email && u.Password == model.Password
                                   select u).SingleOrDefault();

                        if (user == null)
                        {
                            ViewBag.Message = "Login inválido, tente novamente !";
                            return View(model);
                        }
                        else
                        {
                            Session.Add("userid", user.Id);
                            Session.Add("email", user.Email);
                            FormsAuthentication.SetAuthCookie(user.Email, false);
                            return RedirectToAction("Home");
                        }
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Não foi possível processar o login.";
                    System.Web.HttpContext.Current.Trace.Write("UserController.Login() --> " + ex.Message);
                    return View(model);
                }
            }
            else
            {
                ViewBag.Message = "Informe o email e a senha !";
                return View(model);
            }
        }

        public ActionResult Register()
        {
            RegistrationModel model = new RegistrationModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Register(RegistrationModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    User u = new User { Email = model.Email, Password = model.Password, JoinedOn = DateTime.Now };
                    using (MyTasksContext ctx = new MyTasksContext())
                    {
                        ctx.Users.Add(u);
                        ctx.SaveChanges();
                    }
                    return RedirectToAction("Login");

                }
                catch (Exception ex)
                {
                    ViewBag.Message = "O endereço de email ja esta sendo utilizado!";
                    System.Web.HttpContext.Current.Trace.Write("UserController.Register() --> " + ex.Message);
                    return View(model);
                }
            }
            else
            {   ViewBag.Message = "Informe um valor válido !";
                return View(model);
             }

        }

        public ActionResult Recovery()
        {
            EmailModel model = new EmailModel();
            return View(model);
        }

        /// <summary>
        /// Neste método você precisa informar os valores corretos do seu servidor
        /// SMTP
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Recovery(EmailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (MyTasksContext ctx = new MyTasksContext())
                    {
                        var user = (from u in ctx.Users
                                    where u.Email == model.Email
                                    select u).SingleOrDefault();

                        if (user == null)
                        {
                            ViewBag.Message = "O usuário deste email não foi encontrado!";
                            return View(model);
                        }
                        else
                        {
                            // envia email com senha
                            MailMessage m = new MailMessage();
                            m.To.Add(new MailAddress(user.Email));
                            m.From = new MailAddress("admin@mytasks.com");
                            m.Subject = "Recuperar Senha ";
                            m.IsBodyHtml = true;
                            m.Body = "Prezado Usuário, <p/>" +
                               "Use a seguinte senha para realizar o login.<p/>Senha : " + user.Password +
                               "<p/>Admin,<br/>MyTarefas.Net";


                            SmtpClient smtp = new SmtpClient("localhost");
                            smtp.Send(m);
                            ViewBag.Message = "Um email com sua senha foi enviado!";
                            return View(model);
                        } // else
                    } // using
                } 
                catch (Exception ex)
                {
                    ViewBag.Message = "Não foi possível recuperar a senha";
                    System.Web.HttpContext.Current.Trace.Write("UserController.Recovery() --> " + ex.Message);
                    return View(model);
                }
            }
            else
            {
                ViewBag.Message = "Forneça um email válido !";
                return View(model);
            }
        }

        [Authorize]
        public ActionResult Home()
        {
            // get list of projects
            using (MyTasksContext ctx = new MyTasksContext())
            {
                var userid = Int32.Parse(Session["userid"].ToString ());
                var projects = from p in ctx.Projects.Include("Tasks").ToList<Project>()
                               where p.UserId == userid
                               select p;

                return View(projects);
            }
        }

        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }



        public ActionResult ChangePassword()
        {
            ChangePasswordModel model = new ChangePasswordModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (MyTasksContext ctx = new MyTasksContext())
                    {
                        string email = Session["email"].ToString();
                        var user = (from u in ctx.Users
                                    where u.Email == email 
                                    select u).SingleOrDefault();

                        // verifica se a senha naterior é a mesma que a do database
                        if ( user.Password == model.Password)
                        {
                            user.Password = model.NewPassword;
                            ctx.SaveChanges();
                            ViewBag.Message = "A senha foi alterada com sucesso !";
                        }
                        else
                        {
                            ViewBag.Message = "A senha anterior esta incorreta !";
                        }

                    }
                    return View(model);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Não foi possível processar sua requisição.";
                    System.Web.HttpContext.Current.Trace.Write("UserController.ChangePasssword() --> " + ex.Message);
                    return View(model);
                }
            }
            else
            {
                ViewBag.Message = "Informação inválida !";
                return View(model);
            }

        }
	}
}

Views/Task/Add.cshtml
@model MyTasks.Models.TaskModel

@{
    ViewBag.Title = "Adicionar Tarefa";
}

<h2 class="text-primary">Adicionar Tarefa</h2>
<hr />
@using (Html.BeginForm()) 
{
    <div class="form-horizontal">
        @Html.HiddenFor( model => model.ProjectId)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { required = "required" })
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate)
                @Html.ValidationMessageFor(model => model.DueDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Importance, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButton("Importance","b", false) Baixa
                @Html.RadioButton("Importance", "n", true) Normal
                @Html.RadioButton("Importance", "u", false) Urgente
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButton("Status", "i", true) A iniciar
                @Html.RadioButton("Status", "a", false) Em andamento
                @Html.RadioButton("Status", "c", false) Concluída
            </div>
        </div>
    

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar Tarefa" class="btn btn-primary" />
                @Html.ActionLink("Cancelar", "Home", "User", null, new { @class = "btn-primary btn" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10  text-danger">
                  @TempData["message"]
            </div>
        </div>
    </div>
}


@section Scripts {
    <script src="~/Scripts/jquery-ui-1.11.4.js"></script>
    <link href="~/Content/themes/base/all.css" rel="stylesheet" />
    <script>
        $(function () {
            $("#DueDate").datepicker({ dateFormat: "dd/mm/yy" });
        }
     );
    </script>
}

Views/Task/Details.cshtml
@model MyTasks.Models.Task

@{
    ViewBag.Title = "Detalhes da tarefa";
}

<h2 class="text-primary">Tarefas - Detalhes</h2>
<hr />
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Importance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImportanceString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusString)
        </dd>

        <dt>
            Projeto
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Title )
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" }) 
    @Html.ActionLink("Deletar", "Delete", new { id = Model.Id }, new { @class = "btn btn-primary", onclick = "return confirm('Deseja excluir esta tarefa ?')" }) 
    @Html.ActionLink("Listar Tarefas", "List", new { id = Model.ProjectId }, new { @class = "btn btn-primary" })
</p>

Views/Task/Edit.cshtml
@model MyTasks.Models.Task 
@{
    ViewBag.Title = "Editar Tarefa";
}

<h2 class="text-primary">Editar Tarefa</h2>
<hr />
@using (Html.BeginForm()) 
{
    <div class="form-horizontal">
        @Html.HiddenFor( model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { required = "required", size="30" })
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("DueDate", Model.DueDateString , new { size = "10" } )
                @Html.ValidationMessageFor(model => model.DueDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Importance, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButton("Importance","b") Baixa
                @Html.RadioButton("Importance", "n") Normal
                @Html.RadioButton("Importance", "u") Urgente
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButton("Status", "i") A iniciar
                @Html.RadioButton("Status", "a") Em andamento
                @Html.RadioButton("Status", "c") Concluída
            </div>
        </div>
    

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submeter" class="btn btn-primary" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10  text-danger">
                  @TempData["message"]
            </div>
        </div>
    </div>
}


@section Scripts {
    <script src="~/Scripts/jquery-ui-1.11.4.js"></script>
    <link href="~/Content/themes/base/all.css" rel="stylesheet" />
    <script>
        $(function () {
            $("#DueDate").datepicker({ dateFormat: "dd/mm/yy" });
        }
     );
    </script>
}

Views/Task/List.cshtml
@model IEnumerable<MyTasks.Models.Task>

@{
    ViewBag.Title = "Tarefas";
}

<h2 class="text-primary">Tarefas de  [@ViewBag.ProjectTitle]</h2>

 @Html.ActionLink("Adicionar Tarefa", "Add", "Task", new { Id = ViewContext.RouteData.Values["id"] }, null)

 <p></p>
 @foreach (var task in Model)
 {
     <div class="panel panel-primary">
         <div class="panel-body">
             <span class="lead">@task.Title</span>
             <div class="text-success">
                 Data para Realização :
                    @if(task.DueDate == null)
                    { 
                        <span>Nenhuma</span>
                    }
                    else
                    {
                        <span>@task.DueDate</span>
                    }
             </div>
             <p></p>
             @Html.ActionLink("Deletar", "Delete", "Task", new { Id = @task.Id }, 
                                   new { onclick="return confirm('Deseja deletar esta tarefa ?')"})
             | 
             @Html.ActionLink("Detalhes", "Details", "Task", new { Id = @task.Id }, null)
             | 
             @Html.ActionLink("Editar", "Edit", "Task", new { Id = @task.Id }, null) 
            
         </div>
         
     </div>

 }

Views/Task/SearchForm.cshtml
@{
    ViewBag.Title = "Procurar Tarefas";
}

<h2 class="text-primary">Procurar Tarefas</h2>

@using(Ajax.BeginForm("Search", new AjaxOptions {  UpdateTargetId = "results"}))
{
    <input type="text" name="title" placeholder="Título" />
    <input type="submit" value="Procurar" />
    <p></p>
    <div id="results">
    </div>
}

@section Scripts {
   <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
}

Views/Task/SearchResults.cshtml
@model IEnumerable<MyTasks.Models.Task>

<table class="table table-bordered ">
    <tr class="btn-danger">
        <th>
            Projeto
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Importance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Project.Title)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @item.AddedOn.Value.ToString("dd/MM/yyyy")
        </td>
        <td>
           @item.DueDateString
                   
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImportanceString)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StatusString)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Deletar", "Delete", new { id=item.Id } , new { onclick = "return confirm('Deseja deletar esta tarefa ?')" } )
        </td>
    </tr>
}

</table>